update

diff --git a/cvs/src/regress/usr.sbin/ifstated/ifstated,v b/cvs/src/regress/usr.sbin/ifstated/ifstated,v
--- a/cvs/src/regress/usr.sbin/ifstated/ifstated,v
+++ b/cvs/src/regress/usr.sbin/ifstated/ifstated,v
@@ -1,9 +1,15 @@
-head	1.3;
+head	1.4;
 access;
 symbols;
 locks; strict;
 comment	@# @;
 
+
+1.4
+date	2017.08.12.04.40.47;	author rob;	state Exp;
+branches;
+next	1.3;
+commitid	QSf9gi0VQ4zixlLE;
 
 1.3
 date	2017.07.31.18.41.21;	author rob;	state Exp;
@@ -28,14 +34,15 @@ desc
 @@
 
 
-1.3
+1.4
 log
-@Tweak demoted state test, ok jca@@
+@Use vether instead of physical interfaces for temporary carp creation.
+Recommended by and discussed with many.
 @
 text
 @#!/bin/sh
 #
-# $OpenBSD: ifstated,v 1.2 2017/07/30 18:13:38 jca Exp $
+# $OpenBSD: ifstated,v 1.3 2017/07/31 18:41:21 rob Exp $
 #/*
 # * Copyright (c) Rob Pierce <rob@@2keys.ca>
 # *
@@ -66,6 +73,7 @@ SLEEP=10
 cleanup() {
 	ifconfig carp${VHIDA} destroy > /dev/null 2>&1
 	ifconfig carp${VHIDB} destroy > /dev/null 2>&1
+	ifconfig vether${VHIDB} destroy > /dev/null 2>&1
 	rm working/ifstated.conf >/dev/null 2>&1
 	rm working/ifstated.log >/dev/null 2>&1
 	rm working/output.test >/dev/null 2>&1
@@ -88,15 +96,15 @@ skip() {
 
 trap 'skip' INT
 
-# look for a suitable physical interface for carp
-NIC="$(netstat -rn -finet | grep ^default | awk '{ print $8 }')"
-STATUS="$(ifconfig | grep -A5 ^${NIC} | grep status: | awk '{ print $2 }')"
-
-if [ "$STATUS" != "active" ]
+ifconfig vether${VHIDB} create >/dev/null 2>&2
+if [ $? -ne 0 ]
 then
-	echo "No suitable physical interface found."
+	echo "Could not create temporary vether interface."
 	echo SKIPPED
 	exit 0
+else
+	ifconfig vether${VHIDB} up
+	NIC=vether${VHIDB}
 fi
 
 if [ "$(pgrep ifstated)" ]
@@ -198,6 +206,29 @@ case $? in
 1)	fail
 	;;
 esac
+@
+
+
+1.3
+log
+@Tweak demoted state test, ok jca@@
+@
+text
+@d3 1
+a3 1
+# $OpenBSD: ifstated,v 1.2 2017/07/30 18:13:38 jca Exp $
+d34 1
+d57 2
+a58 5
+# look for a suitable physical interface for carp
+NIC="$(netstat -rn -finet | grep ^default | awk '{ print $8 }')"
+STATUS="$(ifconfig | grep -A5 ^${NIC} | grep status: | awk '{ print $2 }')"
+
+if [ "$STATUS" != "active" ]
+d60 1
+a60 1
+	echo "No suitable physical interface found."
+d63 3
 @
 
 
