update

diff --git a/cvs/src/gnu/usr.bin/perl/Makefile.SH,v b/cvs/src/gnu/usr.bin/perl/Makefile.SH,v
--- a/cvs/src/gnu/usr.bin/perl/Makefile.SH,v
+++ b/cvs/src/gnu/usr.bin/perl/Makefile.SH,v
@@ -1,6 +1,7 @@
-head	1.36;
+head	1.39;
 access;
 symbols
+	PERL_5_24_2:1.1.1.18
 	OPENBSD_6_1:1.36.0.4
 	OPENBSD_6_1_BASE:1.36
 	OPENBSD_6_0:1.33.0.4
@@ -109,6 +110,24 @@ locks; strict;
 comment	@# @;
 expand	@o@;
 
+
+1.39
+date	2017.08.14.13.50.31;	author afresh1;	state Exp;
+branches;
+next	1.38;
+commitid	9G1mW67n0iRI6ckT;
+
+1.38
+date	2017.08.14.13.49.43;	author afresh1;	state Exp;
+branches;
+next	1.37;
+commitid	AOpGtCFzbfdujI88;
+
+1.37
+date	2017.08.14.13.48.45;	author afresh1;	state Exp;
+branches;
+next	1.36;
+commitid	CrMEpTqBUsxCMTjx;
 
 1.36
 date	2017.02.05.00.34.32;	author afresh1;	state Exp;
@@ -387,17 +406,25 @@ commitid	B31cAbBIXiCqnL97;
 1.1.1.17
 date	2015.04.25.19.10.09;	author afresh1;	state Exp;
 branches;
-next	;
+next	1.1.1.18;
 commitid	Wpcs5S8qILgEZC7F;
+
+1.1.1.18
+date	2017.08.14.13.45.26;	author afresh1;	state Exp;
+branches;
+next	;
+commitid	fAzrs78vdW2Yfc6A;
 
 
 desc
 @@
 
 
-1.36
+1.39
 log
-@Apply pre-built unicore patch - perl-5.24.1
+@Apply pre-built unicore patch - perl-5.24.2
+
+OK bluhm@@, Reads ok sthen@@
 @
 text
 @#!/bin/sh
@@ -924,7 +951,7 @@ miniperl_objs = $(miniperl_objs_nodt) $(DTRACE_MINI_O)
 perllib_objs  = $(perllib_objs_nodt) $(DTRACE_PERLLIB_O)
 perlmain_objs = perlmain$(OBJ_EXT) $(DTRACE_MAIN_O)
 
-perltoc_pod_prereqs = extra.pods pod/perl5241delta.pod pod/perlapi.pod pod/perlintern.pod pod/perlmodlib.pod
+perltoc_pod_prereqs = extra.pods pod/perl5242delta.pod pod/perlapi.pod pod/perlintern.pod pod/perlmodlib.pod
 generated_pods = pod/perltoc.pod $(perltoc_pod_prereqs)
 generated_headers = uudmap.h bitcount.h mg_data.h
 
@@ -1481,9 +1508,9 @@ pod/perlintern.pod: $(MINIPERL_EXE) autodoc.pl embed.fnc
 pod/perlmodlib.pod: $(MINIPERL_EXE) pod/perlmodlib.PL MANIFEST
 	$(MINIPERL) pod/perlmodlib.PL -q
 
-pod/perl5241delta.pod: pod/perldelta.pod
-	$(RMS) pod/perl5241delta.pod
-	$(LNS) perldelta.pod pod/perl5241delta.pod
+pod/perl5242delta.pod: pod/perldelta.pod
+	$(RMS) pod/perl5242delta.pod
+	$(LNS) perldelta.pod pod/perl5242delta.pod
 
 extra.pods: $(MINIPERL_EXE)
 	-@@test ! -f extra.pods || rm -f `cat extra.pods`
@@ -2097,6 +2124,195 @@ esac
 esac
 
 # ex: set ts=8 sts=4 sw=4 noet:
+@
+
+
+1.38
+log
+@Apply local patches - perl-5.24.2
+
+OK bluhm@@, Reads ok sthen@@
+@
+text
+@d525 1
+a525 1
+perltoc_pod_prereqs = extra.pods pod/perl5242delta.pod pod/perlapi.pod pod/perlintern.pod pod/perlmodlib.pod pod/perluniprops.pod
+@
+
+
+1.37
+log
+@Fix merge issues, remove excess files - match perl-5.24.2 dist
+
+OK bluhm@@, Reads ok sthen@@
+@
+text
+@d467 1
+a467 1
+private = preplibrary \$(CONFIGPM) \$(CONFIGPOD) git_version.h lib/buildcustomize.pl
+d610 1
+d613 7
+a619 7
+git_version.h: lib/Config_git.pl
+
+lib/Config_git.pl: $(MINIPERL_EXE) make_patchnum.pl
+	$(MINIPERL) make_patchnum.pl
+
+# make sure that we recompile perl.c if the git version changes
+perl$(OBJ_EXT): git_version.h
+d785 3
+a787 3
+$(LIBPERL_NONSHR): $(perllib_objs)
+	$(RMS) $(LIBPERL_NONSHR)
+	$(AR) rc $(LIBPERL_NONSHR) $(perllib_objs)
+d789 1
+a789 1
+$(MINIPERL_NONSHR): $(LIBPERL_NONSHR) miniperlmain$(OBJ_EXT) opmini$(OBJ_EXT)  perlmini$(OBJ_EXT)
+d876 27
+a902 27
+$(LIBPERL): $& $(perllib_objs) $(DYNALOADER) $(LIBPERLEXPORT)
+!NO!SUBS!
+	case "$useshrplib" in
+	true)
+		$spitshell >>$Makefile <<'!NO!SUBS!'
+	rm -f $@@
+	$(LD) -o $@@ $(SHRPLDFLAGS) $(perllib_objs) $(DYNALOADER) $(libs)
+!NO!SUBS!
+		case "$osname" in
+		aix)
+			$spitshell >>$Makefile <<'!NO!SUBS!'
+	rm -f libperl$(OBJ_EXT)
+	mv $@@ libperl$(OBJ_EXT)
+	$(AR) qv $(LIBPERL) libperl$(OBJ_EXT)
+!NO!SUBS!
+			;;
+		esac
+		;;
+	*)
+		$spitshell >>$Makefile <<'!NO!SUBS!'
+	rm -f $(LIBPERL)
+	$(AR) rc $(LIBPERL) $(perllib_objs) $(DYNALOADER)
+	@@$(ranlib) $(LIBPERL)
+!NO!SUBS!
+		;;
+	esac
+	$spitshell >>$Makefile <<'!NO!SUBS!'
+a966 4
+	-@@rm -f miniperl.xok
+	$(CC) $(CLDFLAGS) $(NAMESPACEFLAGS) -o $(MINIPERL_EXE) \
+	    $(miniperl_objs) $(libs)
+	$(LDLIBPTH) ./miniperl$(HOST_EXE_EXT) -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
+d1066 1
+a1066 4
+	$(MINIPERL) lib/unicore/mktables -C lib/unicore -P pod -maketest -makelist -p
+#	Commented out so always runs, mktables looks at far more files than we
+#	can in this makefile to decide if needs to run or not
+#	touch uni.data
+d1330 1
+a1330 1
+	-rm -f config.arch config.over $(DTRACE_H)
+d1382 12
+a1393 12
+	-rmdir lib/Net/FTP lib/Module/Load lib/Module/CoreList lib/Module
+	-rmdir lib/Memoize lib/Math/BigInt lib/Math/BigFloat lib/Math lib/MIME
+	-rmdir lib/Locale/Maketext lib/Locale/Codes lib/Locale lib/List/Util
+	-rmdir lib/List lib/JSON/PP lib/JSON lib/IPC lib/IO/Uncompress/Adapter
+	-rmdir lib/IO/Uncompress lib/IO/Socket lib/IO/Compress/Zlib
+	-rmdir lib/IO/Compress/Zip lib/IO/Compress/Gzip lib/IO/Compress/Base
+	-rmdir lib/IO/Compress/Adapter lib/IO/Compress lib/IO
+	-rmdir lib/I18N/LangTags lib/I18N lib/Hash/Util lib/Hash lib/HTTP
+	-rmdir lib/Filter/Util lib/Filter lib/File/Spec lib/ExtUtils/Typemaps
+	-rmdir lib/ExtUtils/ParseXS lib/ExtUtils/MakeMaker/version
+	-rmdir lib/ExtUtils/MakeMaker lib/ExtUtils/Liblist
+	-rmdir lib/ExtUtils/Constant lib/ExtUtils/Command
+@
+
+
+1.36
+log
+@Apply pre-built unicore patch - perl-5.24.1
+@
+text
+@d467 1
+a467 1
+private = preplibrary \$(CONFIGPM) \$(CONFIGPOD) lib/buildcustomize.pl
+d525 1
+a525 1
+perltoc_pod_prereqs = extra.pods pod/perl5241delta.pod pod/perlapi.pod pod/perlintern.pod pod/perlmodlib.pod
+a609 1
+# OpenBSD uses pre-generated lib/Config_git.pl and git_version.h files
+d612 7
+a618 7
+#git_version.h: lib/Config_git.pl
+#
+#lib/Config_git.pl: $(MINIPERL_EXE) make_patchnum.pl
+#	$(MINIPERL) make_patchnum.pl
+#
+## make sure that we recompile perl.c if the git version changes
+#perl$(OBJ_EXT): git_version.h
+d784 3
+a786 3
+#$(LIBPERL_NONSHR): $(perllib_objs)
+#	$(RMS) $(LIBPERL_NONSHR)
+#	$(AR) rc $(LIBPERL_NONSHR) $(perllib_objs)
+d788 1
+a788 1
+$(MINIPERL_NONSHR): miniperlmain$(OBJ_EXT) opmini$(OBJ_EXT)  perlmini$(OBJ_EXT)
+d875 27
+a901 27
+#$(LIBPERL): $& $(perllib_objs) $(DYNALOADER) $(LIBPERLEXPORT)
+#!NO!SUBS!
+#	case "$useshrplib" in
+#	true)
+#		$spitshell >>$Makefile <<'!NO!SUBS!'
+#	rm -f $@@
+#	$(LD) -o $@@ $(SHRPLDFLAGS) $(perllib_objs) $(DYNALOADER) $(libs)
+#!NO!SUBS!
+#		case "$osname" in
+#		aix)
+#			$spitshell >>$Makefile <<'!NO!SUBS!'
+#	rm -f libperl$(OBJ_EXT)
+#	mv $@@ libperl$(OBJ_EXT)
+#	$(AR) qv $(LIBPERL) libperl$(OBJ_EXT)
+#!NO!SUBS!
+#			;;
+#		esac
+#		;;
+#	*)
+#		$spitshell >>$Makefile <<'!NO!SUBS!'
+#	rm -f $(LIBPERL)
+#	$(AR) rc $(LIBPERL) $(perllib_objs) $(DYNALOADER)
+#	@@$(ranlib) $(LIBPERL)
+#!NO!SUBS!
+#		;;
+#	esac
+#	$spitshell >>$Makefile <<'!NO!SUBS!'
+d966 4
+d1069 4
+a1072 1
+	touch uni.data
+d1088 3
+a1090 3
+pod/perl5241delta.pod: pod/perldelta.pod
+	$(RMS) pod/perl5241delta.pod
+	$(LNS) perldelta.pod pod/perl5241delta.pod
+d1336 1
+a1336 1
+	-rm -f $(DTRACE_H)
+d1388 12
+a1399 12
+	-rmdir lib/OpenBSD lib/Net/FTP lib/Module/Load lib/Module/CoreList
+	-rmdir lib/Module lib/Memoize lib/Math/BigInt lib/Math/BigFloat
+	-rmdir lib/Math lib/MIME lib/Locale/Maketext lib/Locale/Codes
+	-rmdir lib/Locale lib/List/Util lib/List lib/JSON/PP lib/JSON lib/IPC
+	-rmdir lib/IO/Uncompress/Adapter lib/IO/Uncompress lib/IO/Socket
+	-rmdir lib/IO/Compress/Zlib lib/IO/Compress/Zip lib/IO/Compress/Gzip
+	-rmdir lib/IO/Compress/Base lib/IO/Compress/Adapter lib/IO/Compress
+	-rmdir lib/IO lib/I18N/LangTags lib/I18N lib/Hash/Util lib/Hash
+	-rmdir lib/HTTP lib/Filter/Util lib/Filter lib/File/Spec
+	-rmdir lib/ExtUtils/Typemaps lib/ExtUtils/ParseXS
+	-rmdir lib/ExtUtils/MakeMaker/version lib/ExtUtils/MakeMaker
+	-rmdir lib/ExtUtils/Liblist lib/ExtUtils/Constant lib/ExtUtils/Command
 @
 
 
@@ -11433,6 +11649,350 @@ a1021 3
 pod/perl5202delta.pod: pod/perldelta.pod
 	$(RMS) pod/perl5202delta.pod
 	$(LNS) perldelta.pod pod/perl5202delta.pod
+@
+
+
+1.1.1.18
+log
+@Import perl-5.24.2
+@
+text
+@d8 1
+a8 1
+	*)  echo "$1" | sed 's/\([^a-zA-Z0-9.:_/-]\)/\\\1/g' ;;
+a22 9
+case "$osname" in
+amigaos)
+	devtty=CONSOLE:
+	;;
+*)
+	devtty=/dev/tty
+	;;
+esac
+
+d224 2
+a225 6
+
+# three object files generated by 'dtrace -G' when dtrace is enabled
+dtrace_perllib_o=''
+dtrace_mini_o=''
+dtrace_main_o=''
+
+d228 4
+a231 8
+	dtrace_h='perldtrace.h'
+	case "$dtraceobject" in
+	define)
+		dtrace_perllib_o='dtrace_perllib$(OBJ_EXT)'
+		dtrace_mini_o='dtrace_mini$(OBJ_EXT)'
+		dtrace_main_o='dtrace_main$(OBJ_EXT)'
+		;;
+	esac
+d251 2
+a315 3
+# Macros to invoke sort the MANIFEST during build
+MANIFEST_SRT = MANIFEST.srt
+
+d348 1
+a348 1
+public = \$(PERL_EXE) utilities
+a351 3
+# The /dev/tty or the moral equivalent.
+devtty = $devtty
+
+d375 2
+a376 4
+
+DTRACE_PERLLIB_O = $dtrace_perllib_o # "dtrace -G" output for perllib_objs
+DTRACE_MINI_O    = $dtrace_mini_o    # "dtrace -G" output for common and mini
+DTRACE_MAIN_O    = $dtrace_main_o    # "dtrace -G" output for perlmain.o
+d438 1
+a438 1
+SH='Makefile.SH cflags.SH config_h.SH makedepend.SH myconfig.SH runtests.SH pod/Makefile.SH'
+d475 1
+a475 1
+c1 = av.c scope.c op.c doop.c doio.c dump.c gv.c hv.c mg.c reentr.c mro_core.c perl.c
+d478 2
+a479 2
+c4 = perlio.c perlapi.c numeric.c mathoms.c locale.c pp_pack.c pp_sort.c caretx.c dquote.c time64.c
+c5 = $(mallocsrc)
+d483 3
+a485 1
+obj1 = $(mallocobj) gv$(OBJ_EXT) toke$(OBJ_EXT) perly$(OBJ_EXT) pad$(OBJ_EXT) regcomp$(OBJ_EXT) dump$(OBJ_EXT) util$(OBJ_EXT) mg$(OBJ_EXT) reentr$(OBJ_EXT) mro_core$(OBJ_EXT) keywords$(OBJ_EXT)
+d487 1
+a487 9
+obj3 = doop$(OBJ_EXT) doio$(OBJ_EXT) regexec$(OBJ_EXT) utf8$(OBJ_EXT) taint$(OBJ_EXT) deb$(OBJ_EXT) universal$(OBJ_EXT) globals$(OBJ_EXT) perlio$(OBJ_EXT) perlapi$(OBJ_EXT) numeric$(OBJ_EXT) mathoms$(OBJ_EXT) locale$(OBJ_EXT) pp_pack$(OBJ_EXT) pp_sort$(OBJ_EXT) caretx$(OBJ_EXT) dquote$(OBJ_EXT) time64$(OBJ_EXT)
+
+# split the objects into 3 exclusive sets: those used by both miniperl and
+# perl, and those used by just one or the other. Doesn't include the
+# actual perl(mini)main.o, nor any dtrace objects.
+
+common_objs    = $(obj1) $(obj2) $(obj3) $(ARCHOBJS)
+mini_only_objs = opmini$(OBJ_EXT) perlmini$(OBJ_EXT)
+main_only_objs = op$(OBJ_EXT)     perl$(OBJ_EXT)
+d489 4
+a492 2
+miniperl_objs_nodt = $(mini_only_objs) $(common_objs) miniperlmain$(OBJ_EXT)
+perllib_objs_nodt  = $(main_only_objs) $(common_objs)
+d494 1
+a494 5
+miniperl_objs = $(miniperl_objs_nodt) $(DTRACE_MINI_O)
+perllib_objs  = $(perllib_objs_nodt) $(DTRACE_PERLLIB_O)
+perlmain_objs = perlmain$(OBJ_EXT) $(DTRACE_MAIN_O)
+
+perltoc_pod_prereqs = extra.pods pod/perl5242delta.pod pod/perlapi.pod pod/perlintern.pod pod/perlmodlib.pod pod/perluniprops.pod
+d560 1
+a560 1
+.c.i:	perl.h config.h
+d564 1
+a564 1
+.c.s:	perl.h config.h
+d568 1
+a568 1
+all: $(FIRSTMAKEFILE) $(MINIPERL_EXE) $(generated_pods) $(private) $(unidatafiles) $(public) $(dynamic_ext) $(nonxs_ext) extras.make $(MANIFEST_SRT)
+d572 1
+a572 6
+$(MANIFEST_SRT):	MANIFEST $(PERL_EXE)
+	@@$(RUN_PERL) Porting/manisort -q || (echo "WARNING: re-sorting MANIFEST"; \
+	    $(RUN_PERL) Porting/manisort -q -o MANIFEST; sh -c true)
+	@@touch $(MANIFEST_SRT)
+
+.PHONY: all utilities
+d586 1
+a586 1
+# Making utilities requires Cwd.  If we have dynamic
+d592 1
+d596 1
+d599 1
+d604 12
+a708 11
+case "$osname" in
+amigaos*)
+$spitshell >>$Makefile <<'!NO!SUBS!'
+perlmain.c: $(MINIPERL_EXE) ext/ExtUtils-Miniperl/pm_to_blib
+	$(MINIPERL) -Ilib -MExtUtils::Miniperl -e 'writemain(\\"perlmain.c", @@ARGV)' DynaLoader $(static_ext)
+
+# The file ext.libs is a list of libraries that must be linked in
+# for static extensions, e.g. -lm -lgdbm, etc.  The individual
+# static extension Makefile's add to it.
+ext.libs: $(static_ext)
+	-@@test -f ext.libs || touch ext.libs
+a709 3
+!NO!SUBS!
+;;
+*)
+a720 2
+;;
+esac
+d747 1
+a747 1
+$(LIBPERL_NONSHR): $(perllib_objs)
+d749 1
+a749 1
+	$(AR) rc $(LIBPERL_NONSHR) $(perllib_objs)
+d793 1
+a793 1
+$(LIBPERL_NONSHR): $(perllib_objs)
+d795 1
+a795 1
+	$(AR) rc $(LIBPERL_NONSHR) $(perllib_objs)
+d822 2
+a823 2
+	case "$dtraceobject" in
+	define)
+d825 2
+a826 2
+$(DTRACE_MINI_O): perldtrace.d $(miniperl_objs_nodt)
+	$(DTRACE) -G -s perldtrace.d -o $(DTRACE_MINI_O) $(miniperl_objs_nodt)
+d828 2
+a829 5
+$(DTRACE_PERLLIB_O): perldtrace.d $(perllib_objs_nodt)
+	$(DTRACE) -G -s perldtrace.d -o $(DTRACE_PERLLIB_O) $(perllib_objs_nodt)
+
+$(DTRACE_MAIN_O): perldtrace.d perlmain$(OBJ_EXT)
+	$(DTRACE) -G -s perldtrace.d -o $(DTRACE_MAIN_O) perlmain$(OBJ_EXT)
+d835 1
+a835 1
+$(LIBPERL): $& $(perllib_objs) $(DYNALOADER) $(LIBPERLEXPORT)
+d841 1
+a841 1
+	$(LD) -o $@@ $(SHRPLDFLAGS) $(perllib_objs) $(DYNALOADER) $(libs)
+d856 1
+a856 1
+	$(AR) rc $(LIBPERL) $(perllib_objs) $(DYNALOADER)
+d877 1
+a877 1
+#    (so that lib/buildcustomize.pl is always available. This simplifies things)
+a884 10
+	amigaos*)
+		$spitshell >>$Makefile <<'!NO!SUBS!'
+lib/buildcustomize.pl: $& $(miniperl_objs) write_buildcustomize.pl
+	-@@rm -f miniperl.xok
+	$(CC) $(CLDFLAGS) -o $(MINIPERL_EXE) \
+	    $(miniperl_objs) $(libs)
+#	$(LDLIBPTH) ./miniperl$(HOST_EXE_EXT) -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
+	$(MINIPERL) -f write_buildcustomize.pl
+!NO!SUBS!
+		;;
+d887 2
+a888 2
+lib/buildcustomize.pl: $& $(miniperl_objs)
+	$(CC) -o $(MINIPERL_EXE) $(CLDFLAGS) $(miniperl_objs) $(libs)
+d895 2
+a896 2
+lib/buildcustomize.pl: $& $(miniperl_objs) write    ldcustomize.pl
+	$(CC) -o $(MINIPERL_EXE) $(miniperl_objs    libs)
+d915 1
+a915 1
+lib/buildcustomize.pl: $& $(miniperl_objs) write_buildcustomize.pl
+d918 1
+a918 1
+	    $(miniperl_objs) $(libs)
+d926 1
+a926 1
+lib/buildcustomize.pl: \$& \$(miniperl_objs) write_buildcustomize.pl
+d935 1
+a935 1
+lib/buildcustomize.pl: $& $(miniperl_objs) write_buildcustomize.pl
+d938 1
+a938 1
+	    $(miniperl_objs) $(libs)
+d948 1
+a948 1
+$(PERL_EXE): $& $(perlmain_objs) $(LIBPERL) $(static_ext) ext.libs $(PERLEXPORT) write_buildcustomize.pl
+d950 1
+a950 20
+!NO!SUBS!
+
+        case $osname in
+	# In AmigaOS the Perl executable needs to be linked with -ldl,
+	# but none of the other executables should be.
+        amigaos) $spitshell >>$Makefile <<'!NO!SUBS!'
+	$(SHRPENV) $(CC) -o perl $(CLDFLAGS) $(CCDLFLAGS) $(perlmain_objs) $(LLIBPERL) $(static_ext) `cat ext.libs` $(libs) -ldl
+!NO!SUBS!
+        ;;
+        os390) $spitshell >>$Makefile <<'!NO!SUBS!'
+	$(SHRPENV) $(CC) -o perl $(CLDFLAGS) $(CCDLFLAGS) $(perlmain_objs) $(LLIBPERL) $(static_ext) `cat ext.libs` $(libs)
+!NO!SUBS!
+        ;;
+        *) $spitshell >>$Makefile <<'!NO!SUBS!'
+	$(SHRPENV) $(CC) -o perl $(CLDFLAGS) $(CCDLFLAGS) $(perlmain_objs) $(static_ext) $(LLIBPERL) `cat ext.libs` $(libs)
+!NO!SUBS!
+        ;;
+        esac
+
+	$spitshell >>$Makefile <<'!NO!SUBS!'
+d1019 3
+a1021 3
+pod/perl5242delta.pod: pod/perldelta.pod
+	$(RMS) pod/perl5242delta.pod
+	$(LNS) perldelta.pod pod/perl5242delta.pod
+d1210 1
+a1210 1
+	$(MINIPERL) make_ext.pl $@@ $(MAKE_EXT_ARGS) MAKE="$(MAKE)" LIBPERL_A=$(LIBPERL) LINKTYPE=static $(STATIC_LDFLAGS)
+d1213 1
+a1213 1
+	$(MINIPERL) make_ext.pl $@@ $(MAKE_EXT_ARGS) MAKE="$(MAKE)" LIBPERL_A=$(LIBPERL) LINKTYPE=dynamic
+d1216 1
+a1216 1
+	$(MINIPERL) make_ext.pl $@@ $(MAKE_EXT_ARGS) MAKE="$(MAKE)" LIBPERL_A=$(LIBPERL) LINKTYPE=static $(STATIC_LDFLAGS)
+d1219 1
+a1219 1
+	$(MINIPERL) make_ext.pl $@@ $(MAKE_EXT_ARGS) MAKE="$(MAKE)" LIBPERL_A=$(LIBPERL)
+d1236 1
+a1236 1
+clean:		realclean
+a1245 1
+	rm -f $(MANIFEST_SRT)
+d1268 10
+d1282 1
+d1285 1
+a1285 1
+	$(MINIPERL) make_ext.pl --target=$(CLEAN) $$x MAKE="$(MAKE)" ; \
+d1315 23
+a1337 24
+	-rmdir lib/version lib/threads lib/inc/ExtUtils lib/inc lib/encoding
+	-rmdir lib/autodie/exception lib/autodie/Scope lib/autodie lib/XS
+	-rmdir lib/Win32API lib/VMS lib/Unicode/Collate/Locale
+	-rmdir lib/Unicode/Collate/CJK lib/Unicode/Collate lib/Tie/Hash
+	-rmdir lib/Thread lib/Text lib/Test/use lib/Test/Tester
+	-rmdir lib/Test/Builder/Tester lib/Test/Builder/IO lib/Test/Builder
+	-rmdir lib/Test lib/Term lib/TAP/Parser/YAMLish
+	-rmdir lib/TAP/Parser/SourceHandler lib/TAP/Parser/Scheduler
+	-rmdir lib/TAP/Parser/Result lib/TAP/Parser/Iterator lib/TAP/Parser
+	-rmdir lib/TAP/Harness lib/TAP/Formatter/File
+	-rmdir lib/TAP/Formatter/Console lib/TAP/Formatter lib/TAP
+	-rmdir lib/Sys/Syslog lib/Sys lib/Sub lib/Search lib/Scalar
+	-rmdir lib/Pod/Text lib/Pod/Simple lib/Pod/Perldoc lib/PerlIO/via
+	-rmdir lib/PerlIO lib/Perl lib/Parse/CPAN lib/Parse lib/Params
+	-rmdir lib/Net/FTP lib/Module/Load lib/Module/CoreList lib/Module
+	-rmdir lib/Memoize lib/Math/BigInt lib/Math/BigFloat lib/Math lib/MIME
+	-rmdir lib/Locale/Maketext lib/Locale/Codes lib/Locale lib/List/Util
+	-rmdir lib/List lib/JSON/PP lib/JSON lib/IPC lib/IO/Uncompress/Adapter
+	-rmdir lib/IO/Uncompress lib/IO/Socket lib/IO/Compress/Zlib
+	-rmdir lib/IO/Compress/Zip lib/IO/Compress/Gzip lib/IO/Compress/Base
+	-rmdir lib/IO/Compress/Adapter lib/IO/Compress lib/IO
+	-rmdir lib/I18N/LangTags lib/I18N lib/Hash/Util lib/Hash lib/HTTP
+	-rmdir lib/Filter/Util lib/Filter lib/File/Spec lib/ExtUtils/Typemaps
+	-rmdir lib/ExtUtils/ParseXS lib/ExtUtils/MakeMaker/version
+d1345 5
+a1349 6
+	-rmdir lib/Compress/Raw lib/Compress lib/Carp lib/CPAN/Plugin
+	-rmdir lib/CPAN/Meta/History lib/CPAN/Meta lib/CPAN/LWP
+	-rmdir lib/CPAN/Kwalify lib/CPAN/HTTP lib/CPAN/FTP lib/CPAN/Exception
+	-rmdir lib/CPAN/API lib/CPAN lib/Attribute lib/Archive/Tar lib/Archive
+	-rmdir lib/App/Prove/State/Result lib/App/Prove/State lib/App/Prove
+	-rmdir lib/App lib/Amiga
+a1368 9
+cscopeflags = -Rb  # Recursive, build-only.
+
+.PHONY:	cscope
+# To query the cscope.out "cscope -dLnsymbol" where n = 0 means uses,
+# 1 = definitions, 2 = callees, 3 = callers, for example
+# "cscope -dL1Perl_mg_set" or run cscope interactively (no arguments).
+cscope.out cscope: $(c) $(h)
+	cscope $(cscopeflags)
+
+d1391 2
+a1392 2
+depend: makedepend $(DTRACE_H) $(generated_headers)
+	sh ./makedepend MAKE="$(MAKE)" cflags
+d1413 2
+a1414 1
+	$(dynamic_ext) $(TEST_PERL_DLL) runtests $(generated_pods)
+d1421 1
+a1421 1
+	\$(dynamic_ext) \$(TEST_PERL_DLL) runtests \
+d1457 2
+d1460 2
+d1478 1
+a1478 1
+	$(MINIPERL) make_ext.pl $(dynamic_ext_re) MAKE="$(MAKE)" LIBPERL_A=$(LIBPERL) LINKTYPE=dynamic
+d1519 1
+a1519 1
+	PERL_VALGRIND=1 VALGRIND='$(VALGRIND)' TESTFILE=harness $(RUN_TESTS) choose
+d1526 1
+a1526 1
+# minitest can't depend on lib/Config.pm because that might be where miniperl
+d1528 1
+a1528 1
+minitest_prep:
+d1534 2
+a1535 9
+	- cd t && (rm -f $(PERL_EXE); $(LNS) ../$(MINIPERL_EXE) $(PERL_EXE))
+
+MINITEST_TESTS = base/*.t comp/*.t cmd/*.t run/*.t io/*.t re/*.t opbasic/*.t op/*.t uni/*.t perf/*.t
+
+minitest: $(MINIPERL_EXE) minitest_prep
+	- cd t && $(RUN_PERL) TEST $(MINITEST_TESTS) <$(devtty)
+
+minitest-notty minitest_notty: $(MINIPERL_EXE) minitest_prep
+	- cd t && PERL_SKIP_TTY_TEST=1 $(RUN_PERL) TEST $(MINITEST_TESTS)
+a1598 3
+TAGS: $(c1) $(c2) $(c3) $(c4) $(c5) $(h)
+	etags $(c1) $(c2) $(c3) $(c4) $(c5) $(h)
+
+d1617 38
 @
 
 
