update

diff --git a/cvs/src/usr.bin/ctfconv/ctfstrip,v b/cvs/src/usr.bin/ctfconv/ctfstrip,v
--- a/cvs/src/usr.bin/ctfconv/ctfstrip,v
+++ b/cvs/src/usr.bin/ctfconv/ctfstrip,v
@@ -1,9 +1,15 @@
-head	1.3;
+head	1.4;
 access;
 symbols;
 locks; strict;
 comment	@# @;
 
+
+1.4
+date	2017.08.12.16.33.11;	author jasper;	state Exp;
+branches;
+next	1.3;
+commitid	Z1Frx3oOoHZminFm;
 
 1.3
 date	2017.08.11.15.08.16;	author jasper;	state Exp;
@@ -28,19 +34,21 @@ desc
 @@
 
 
-1.3
+1.4
 log
-@- use mktemp to provide the tempfile name and clean it up properly
-- set strict posix mode
+@fallback to strip(1) in case ctfconv(1) couldn't handle the file (i.e. when
+the input file lacks useful debug sections).
+adjust option handling accordingly to pass any flags not handled by
+ctfstrip(1) down to strip(1).
 
-ok mpi@@
+help and ok mpi@@ tb@@
 @
 text
 @#!/bin/sh
 #
-# $OpenBSD: ctfstrip,v 1.2 2017/08/11 14:24:24 mpi Exp $
+# $OpenBSD: ctfstrip,v 1.3 2017/08/11 15:08:16 jasper Exp $
 #
-# Copyright (c) 2017 Martin Pieuchot 
+# Copyright (c) 2017 Martin Pieuchot
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -65,14 +73,20 @@ trap "cleanup" 1 2 3 13 15
 
 USAGE="usage: ${0##*/} [-S] [-o outfile] file"
 
-while getopts "o:S" opt; do
-	case $opt in
-	S)	STRIPFLAG=-g;;
-	o)	OUTFILE="${OPTARG}";;
-	*)	print -u2 "${USAGE}"; exit 1;;
+for arg in "$@@"; do
+	if [ -n "$OSET" ]; then
+		OUTFILE="$arg"
+		unset OSET
+		shift
+		continue
+	fi
+	case "$arg" in
+	-o)	OSET=1; shift; continue;;
+	-S)	STRIPFLAG=-g; shift; continue;;
 	esac
+	shift
+	set -- "$@@" "$arg"
 done
-shift $((OPTIND-1))
 
 if [[ $# == 0 ]]; then
 	print -u2 "${USAGE}";
@@ -81,17 +95,61 @@ fi
 
 LABEL="unknown"
 TMPFILE=$(mktemp /tmp/.ctf.XXXXXXXXXX)
+INFILE=$(eval "echo \${$#}")
 
 # Extract kernel version
-if [[ "$1" == bsd* ]]; then
-	LABEL=`what $1 |tr -d '\n'|awk -F"$1	" '{ print $2 '\n' }'`
+if [[ "$INFILE" == bsd* ]]; then
+	LABEL=`what $INFILE |tr -d '\n'|awk -F"${INFILE}	" '{ print $2 '\n' }'`
 fi
 
+# If ctfstrip was passed a file that lacks useful debug sections, ctfconv will fail.
+# So try to run ctfconv and silently fallback to plain strip(1) if that failed.
+ctfconv -o ${TMPFILE} -l "${LABEL}" ${INFILE} 2> /dev/null
+
+if [[ $? == 0 ]]; then
+        objcopy --add-section .SUNW_ctf=${TMPFILE} ${STRIPFLAG} ${INFILE} ${OUTFILE}
+else
+        strip ${STRIPFLAG} $@@ -o ${OUTFILE} ${INFILE}
+fi
+
+rm -f ${TMPFILE}
+@
+
+
+1.3
+log
+@- use mktemp to provide the tempfile name and clean it up properly
+- set strict posix mode
+
+ok mpi@@
+@
+text
+@d3 1
+a3 1
+# $OpenBSD: ctfstrip,v 1.2 2017/08/11 14:24:24 mpi Exp $
+d5 1
+a5 1
+# Copyright (c) 2017 Martin Pieuchot 
+d30 10
+a39 5
+while getopts "o:S" opt; do
+	case $opt in
+	S)	STRIPFLAG=-g;;
+	o)	OUTFILE="${OPTARG}";;
+	*)	print -u2 "${USAGE}"; exit 1;;
+d41 2
+a43 1
+shift $((OPTIND-1))
+d52 1
+d55 2
+a56 2
+if [[ "$1" == bsd* ]]; then
+	LABEL=`what $1 |tr -d '\n'|awk -F"$1	" '{ print $2 '\n' }'`
+d59 9
+a67 3
 ctfconv -o ${TMPFILE} -l "${LABEL}" $1 || cleanup
 
 objcopy --add-section .SUNW_ctf=${TMPFILE} ${STRIPFLAG} $1 ${OUTFILE}
-
-rm -f ${TMPFILE}
 @
 
 
