update

diff --git a/cvs/ports/lang/rust/patches/patch-src_etc_rust-gdb,v b/cvs/ports/lang/rust/patches/patch-src_etc_rust-gdb,v
--- a/cvs/ports/lang/rust/patches/patch-src_etc_rust-gdb,v
+++ b/cvs/ports/lang/rust/patches/patch-src_etc_rust-gdb,v
@@ -1,4 +1,4 @@
-head	1.2;
+head	1.3;
 access;
 symbols
 	OPENBSD_6_1:1.2.0.2
@@ -10,6 +10,12 @@ symbols
 locks; strict;
 comment	@# @;
 
+
+1.3
+date	2017.06.17.02.06.53;	author danj;	state Exp;
+branches;
+next	1.2;
+commitid	hI8KpqsP1qgu63cc;
 
 1.2
 date	2017.02.15.12.52.35;	author landry;	state Exp;
@@ -28,6 +34,42 @@ desc
 @@
 
 
+1.3
+log
+@Update to rust-1.18.0
+
+From semarie (maintainer)
+@
+text
+@$OpenBSD: patch-src_etc_rust-gdb,v 1.2 2017/02/15 12:52:35 landry Exp $
+only compatible with egdb (gdb from ports)
+Index: src/etc/rust-gdb
+--- src/etc/rust-gdb.orig
++++ src/etc/rust-gdb
+@@@@ -12,6 +12,11 @@@@
+ # Exit if anything fails
+ set -e
+ 
++if ! command -v egdb; then
++	echo "error: rust-gdb requires devel/gdb to be installed" >&2
++	exit 1
++fi
++
+ # Find out where the pretty printer Python module is
+ RUSTC_SYSROOT=`rustc --print=sysroot`
+ GDB_PYTHON_MODULE_DIRECTORY="$RUSTC_SYSROOT/lib/rustlib/etc"
+@@@@ -19,7 +24,7 @@@@ GDB_PYTHON_MODULE_DIRECTORY="$RUSTC_SYSROOT/lib/rustli
+ # Run GDB with the additional arguments that load the pretty printers
+ # Set the environment variable `RUST_GDB` to overwrite the call to a
+ # different/specific command (defaults to `gdb`).
+-RUST_GDB="${RUST_GDB:-gdb}"
++RUST_GDB="${RUST_GDB:-egdb}"
+ PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIRECTORY" ${RUST_GDB} \
+   -d "$GDB_PYTHON_MODULE_DIRECTORY" \
+   -iex "add-auto-load-safe-path $GDB_PYTHON_MODULE_DIRECTORY" \
+@
+
+
 1.2
 log
 @Update to rust 1.15.1.
@@ -43,28 +85,22 @@ Tested by semarie@@ and myself on i386 & amd64.
 All the hard work and countless build hours by semarie@@, thanks!
 @
 text
-@$OpenBSD: patch-src_etc_rust-gdb,v 1.1 2016/01/13 07:39:08 semarie Exp $
-only compatible with egdb (gdb from ports)
+@d1 1
+a1 1
+$OpenBSD: patch-src_etc_rust-gdb,v 1.1 2016/01/13 07:39:08 semarie Exp $
+d3 4
+a6 3
 --- src/etc/rust-gdb.orig	Tue Jan 31 01:29:51 2017
 +++ src/etc/rust-gdb	Sun Feb  5 15:40:37 2017
 @@@@ -12,12 +12,17 @@@@
- # Exit if anything fails
- set -e
+d18 1
+a18 1
  
-+if ! command -v egdb; then
-+	echo "error: rust-gdb requires devel/gdb to be installed" >&2
-+	exit 1
-+fi
-+
- # Find out where the pretty printer Python module is
- RUSTC_SYSROOT=`rustc --print=sysroot`
- GDB_PYTHON_MODULE_DIRECTORY="$RUSTC_SYSROOT/lib/rustlib/etc"
- 
- # Run GDB with the additional arguments that load the pretty printers
+d20 5
+a24 2
 -PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIRECTORY" gdb \
 +PYTHONPATH="$PYTHONPATH:$GDB_PYTHON_MODULE_DIRECTORY" egdb \
-   -d "$GDB_PYTHON_MODULE_DIRECTORY" \
-   -iex "add-auto-load-safe-path $GDB_PYTHON_MODULE_DIRECTORY" \
+a26 1
    "$@@"
 @
 
