update

diff --git a/cvs/ports/security/password-store/patches/patch-src_password-store_sh,v b/cvs/ports/security/password-store/patches/patch-src_password-store_sh,v
--- a/cvs/ports/security/password-store/patches/patch-src_password-store_sh,v
+++ b/cvs/ports/security/password-store/patches/patch-src_password-store_sh,v
@@ -1,4 +1,4 @@
-head	1.2;
+head	1.3;
 access;
 symbols
 	OPENBSD_6_1:1.2.0.2
@@ -12,6 +12,12 @@ symbols
 locks; strict;
 comment	@# @;
 
+
+1.3
+date	2017.06.28.13.16.49;	author ajacoutot;	state Exp;
+branches;
+next	1.2;
+commitid	n7rHKfiQzE9rDBAA;
 
 1.2
 date	2017.03.07.08.53.17;	author bentley;	state Exp;
@@ -37,25 +43,18 @@ desc
 @@
 
 
-1.2
+1.3
 log
-@Update to password-store-1.7.
+@Our cp(1), mv(1) and rm(1) support `-v' now.
 
-From David Dalhlberg (maintainer). Thanks!
+ok sthen@@
 @
 text
-@$OpenBSD$
---- src/password-store.sh.orig	Sun Feb 26 18:52:16 2017
-+++ src/password-store.sh	Tue Feb 28 14:17:12 2017
-@@@@ -316,14 +316,14 @@@@ cmd_init() {
- 
- 	if [[ $# -eq 1 && -z $1 ]]; then
- 		[[ ! -f "$gpg_id" ]] && die "Error: $gpg_id does not exist and so cannot be removed."
--		rm -v -f "$gpg_id" || exit 1
-+		rm -f "$gpg_id" || exit 1
- 		if [[ -n $INNER_GIT_DIR ]]; then
- 			git -C "$INNER_GIT_DIR" rm -qr "$gpg_id"
- 			git_commit "Deinitialize ${gpg_id}${id_path:+ ($id_path)}."
+@$OpenBSD: patch-src_password-store_sh,v 1.2 2017/03/07 08:53:17 bentley Exp $
+Index: src/password-store.sh
+--- src/password-store.sh.orig
++++ src/password-store.sh
+@@@@ -323,7 +323,7 @@@@ cmd_init() {
  		fi
  		rmdir -p "${gpg_id%/*}" 2>/dev/null
  	else
@@ -122,15 +121,6 @@ text
  	set_gpg_recipients "$(dirname "$path")"
  	local passfile="$PREFIX/$path.gpg"
  	set_git "$passfile"
-@@@@ -561,7 +566,7 @@@@ cmd_delete() {
- 
- 	[[ $force -eq 1 ]] || yesno "Are you sure you would like to delete $path?"
- 
--	rm $recursive -f -v "$passfile"
-+	rm $recursive -f "$passfile"
- 	set_git "$passfile"
- 	if [[ -n $INNER_GIT_DIR && ! -e $passfile ]]; then
- 		git -C "$INNER_GIT_DIR" rm -qr "$passfile"
 @@@@ -595,7 +600,7 @@@@ cmd_copy_move() {
  	echo "$old_path"
  	[[ -e $old_path ]] || die "Error: $1 is not in the password store."
@@ -158,6 +148,40 @@ text
  		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
  		git_add_file "$new_path" "Copy ${1} to ${2}."
  	fi
+@
+
+
+1.2
+log
+@Update to password-store-1.7.
+
+From David Dalhlberg (maintainer). Thanks!
+@
+text
+@d1 5
+a5 12
+$OpenBSD$
+--- src/password-store.sh.orig	Sun Feb 26 18:52:16 2017
++++ src/password-store.sh	Tue Feb 28 14:17:12 2017
+@@@@ -316,14 +316,14 @@@@ cmd_init() {
+ 
+ 	if [[ $# -eq 1 && -z $1 ]]; then
+ 		[[ ! -f "$gpg_id" ]] && die "Error: $gpg_id does not exist and so cannot be removed."
+-		rm -v -f "$gpg_id" || exit 1
++		rm -f "$gpg_id" || exit 1
+ 		if [[ -n $INNER_GIT_DIR ]]; then
+ 			git -C "$INNER_GIT_DIR" rm -qr "$gpg_id"
+ 			git_commit "Deinitialize ${gpg_id}${id_path:+ ($id_path)}."
+a71 9
+@@@@ -561,7 +566,7 @@@@ cmd_delete() {
+ 
+ 	[[ $force -eq 1 ]] || yesno "Are you sure you would like to delete $path?"
+ 
+-	rm $recursive -f -v "$passfile"
++	rm $recursive -f "$passfile"
+ 	set_git "$passfile"
+ 	if [[ -n $INNER_GIT_DIR && ! -e $passfile ]]; then
+ 		git -C "$INNER_GIT_DIR" rm -qr "$passfile"
 @
 
 
